name: prs-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: PRS.sln  

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore and build the application
      run: |
        dotnet restore
        dotnet build -c Release --no-restore

    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  run: dotnet test

    - name: Increase revision number
      shell: pwsh
      run: |
        $xml_file = "./src/prs.csproj"
    
        $package_version = (Select-String -Path $xml_file -Pattern '<PackageVersion>(.*?)<\/PackageVersion>' -AllMatches).Matches.Groups[1].Value
        Write-Host "Current PackageVersion: $package_version"
    
        $version_parts = $package_version -split '\.'
        $pmajor, $pminor, $pbuild, $prevision = $version_parts
        $prevision = [int]$prevision + 1
        $new_package_version = "$pmajor.$pminor.$pbuild.$prevision"
        Write-Host "New PackageVersion: $new_package_version"
    
        (Get-Content $xml_file) -replace '<PackageVersion>.*<\/PackageVersion>', "<PackageVersion>$new_package_version</PackageVersion>" | Set-Content $xml_file

        echo "BRANCH_NAME=update-package-version-$prevision" >> $GITHUB_ENV
        WRITE-HOST "${{ env.BRANCH_NAME }}"
        echo "NEW_PACKAGE_VERSION=$new_package_version" >> $GITHUB_ENV
        WRITE-HOST "${{ env.NEW_PACKAGE_VERSION }}"
    
    - name: Create Temporary Branch
      run: |
        git config user.name "prs"
        git config user.email ""
        
        # Use the BRANCH_NAME environment variable to create the branch
        git checkout -b "${{ env.BRANCH_NAME }}"
        git add .
        git commit -m "Update revision number to ${{ env.NEW_PACKAGE_VERSION }}"
        git push origin "${{ env.BRANCH_NAME }}"
    
    - name: Merge Temporary Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create --title "Update revision number" --body "Automated update of PackageVersion" --base main --head "${{ env.BRANCH_NAME }}"
        gh pr merge --merge --auto --delete-branch
