name: prs-release
on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: PRS.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build -c Release

    - name: Generate release files
      run: dotnet publish -r win-x64 -c Release --sc true -o ./publish ./src/PRS.csproj

    - name: Setup .NET global tool
      id: setup-global-tool
      run: |
        dotnet tool update --global PRS
